package net.kikin.nubecita.core.posting

import kotlinx.collections.immutable.ImmutableList
import kotlinx.collections.immutable.persistentListOf

/**
 * BCP-47 language tags shown by Nubecita's per-post language picker —
 * a port of the `code2`-tagged subset of `bsky-app`'s `LANGUAGES`
 * constant
 * (https://github.com/bluesky-social/social-app/blob/main/src/locale/languages.ts).
 *
 * The upstream `LANGUAGES` array enumerates ISO-639 entries with both
 * `code3` and (sometimes-empty) `code2`. The picker UI at
 * `src/components/dialogs/LanguageSelectDialog.tsx` filters to entries
 * with `code2 != ''` (BCP-47 normalizes to 2-letter codes when one
 * exists) — we mirror that filter here so users see the same set of
 * 184 selectable tags as the official client.
 *
 * Resync with upstream when their list grows or shrinks (rare in
 * practice — once a year tops). Refresh procedure:
 * `gh api repos/bluesky-social/social-app/contents/src/locale/languages.ts | jq -r .content | base64 -d | grep -oE "code2: '[a-z]{2}(-[A-Za-z]+)*'" | sed -E "s/code2: '(.*)'/\1/" | sort -u`
 *
 * Display names are NOT shipped here. UI consumers render each tag via
 * `Locale.forLanguageTag(tag).getDisplayName(Locale.getDefault())` so
 * users on, say, a French phone see "Anglais" instead of "English"
 * without us shipping translation tables.
 */
val BLUESKY_LANGUAGE_TAGS: ImmutableList<String> =
    persistentListOf(
        "aa",
        "ab",
        "ae",
        "af",
        "ak",
        "am",
        "an",
        "ar",
        "as",
        "av",
        "ay",
        "az",
        "ba",
        "be",
        "bg",
        "bh",
        "bi",
        "bm",
        "bn",
        "bo",
        "br",
        "bs",
        "ca",
        "ce",
        "ch",
        "co",
        "cr",
        "cs",
        "cu",
        "cv",
        "cy",
        "da",
        "de",
        "dv",
        "dz",
        "ee",
        "el",
        "en",
        "eo",
        "es",
        "et",
        "eu",
        "fa",
        "ff",
        "fi",
        "fj",
        "fo",
        "fr",
        "fy",
        "ga",
        "gd",
        "gl",
        "gn",
        "gu",
        "gv",
        "ha",
        "he",
        "hi",
        "ho",
        "hr",
        "ht",
        "hu",
        "hy",
        "hz",
        "ia",
        "id",
        "ie",
        "ig",
        "ii",
        "ik",
        "io",
        "is",
        "it",
        "iu",
        "ja",
        "jv",
        "ka",
        "kg",
        "ki",
        "kj",
        "kk",
        "kl",
        "km",
        "kn",
        "ko",
        "kr",
        "ks",
        "ku",
        "kv",
        "kw",
        "ky",
        "la",
        "lb",
        "lg",
        "li",
        "ln",
        "lo",
        "lt",
        "lu",
        "lv",
        "mg",
        "mh",
        "mi",
        "mk",
        "ml",
        "mn",
        "mr",
        "ms",
        "mt",
        "my",
        "na",
        "nb",
        "nd",
        "ne",
        "ng",
        "nl",
        "nn",
        "no",
        "nr",
        "nv",
        "ny",
        "oc",
        "oj",
        "om",
        "or",
        "os",
        "pa",
        "pi",
        "pl",
        "ps",
        "pt",
        "qu",
        "rm",
        "rn",
        "ro",
        "ru",
        "rw",
        "sa",
        "sc",
        "sd",
        "se",
        "sg",
        "si",
        "sk",
        "sl",
        "sm",
        "sn",
        "so",
        "sq",
        "sr",
        "ss",
        "st",
        "su",
        "sv",
        "sw",
        "ta",
        "te",
        "tg",
        "th",
        "ti",
        "tk",
        "tl",
        "tn",
        "to",
        "tr",
        "ts",
        "tt",
        "tw",
        "ty",
        "ug",
        "uk",
        "ur",
        "uz",
        "ve",
        "vi",
        "vo",
        "wa",
        "wo",
        "xh",
        "yi",
        "yo",
        "za",
        "zh",
        "zu",
    )
